export const NOT_FOUND = 'Not found'
export const EMPTY_FIELD = 'Please add all fields'
export const PROMT_NAME = 'Please add a name'
export const PROMT_EMAIL = 'Please add an email'
export const PROMT_PASSOWRD = 'Please add a password'
export const DEFAULT_AVATAR = 'https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y'
export const ALREADY_EXIST = 'User already exists'
export const INVALID_DATA = 'Invalid user data'
export const INVALID_CREDENTIALS = 'Invalid credentials'
export const NOT_AUTHORIZED = 'Not authorized'
export const NO_TOKEN = 'Not authorized, no token'
